const restaurants = [
  {
    id: 1,
    name: "Salt Fried Chicken",
    location: "Kadikoy",
    type: "Fried Chicken",
    rating: 4.3,
    logo: "/images/restaurants/saltFried.png",
    desc: "🐔Lezzetin tahtını beraber kuralım!👑😎 Sadece bir tavuk değil tutku da sunduğumuz Salt’ta Şehrin En İyisiyiz!🐔🫶🏻👯‍♀️",
  },
  {
    id: 2,
    name: "Zula",
    location: "Besiktas",
    type: "Burger",
    rating: 4.7,
    logo: "/images/restaurants/zula.png",
    desc: "Crisp, hearty, and flavor-packed—Zula's menu is a haven for burger and hot dog aficionados alike. Each burger is a masterpiece of juiciness and taste, while their hot dogs are a splendid blend of classic and inventive, wrapped in a perfectly toasted bun. Zula promises a bite that's both nostalgic and novel, leaving your taste buds dancing with delight. A culinary haven where every meal is an unforgettable adventure. 🍔🌭✨",
  },
  {
    id: 3,
    name: "Monster TeaShop",
    location: "Besiktas",
    type: "Boba Tea",
    rating: 4.1,
    logo: "/images/restaurants/monster.png",
    desc: "Refreshing, playful, and bursting with flavor—Monster TeaShop's boba teas are a swirl of delight in every sip. With vibrant, hand-picked ingredients and pearls of chewy boba, each cup is a unique journey through taste and texture. Dive into a refreshing escape; it's not just tea, it's an experience. 🍵✨",
  },
  {
    id: 4,
    name: "Akali",
    location: "Kadikoy",
    type: "Burger",
    rating: 3.3,
    logo: "/images/restaurants/akali.png",
    desc: "Juicy, daring, and utterly satisfying—Akali's burgers pack a punch of flavors in every bite. With melt-in-your-mouth cheese and a signature sauce that dances on your taste buds, each burger is a culinary adventure waiting to be savored. A small bite, a giant leap into burger bliss. 🍔✨",
  },
];
